#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DEFAULTENV=$DIR/default.env
NODEENV=$DIR/node.env

if [ -f "$DEFAULTENV" ]; then source $DEFAULTENV; fi
if [ -f "$NODEENV" ]; then source $NODEENV; fi

while [[ $# -gt 0 ]]; do
	key="$1"
	shift
	found=""

	# if key starts with -- indicating a set field
	[[ "$key" == --* ]] && found="1"

	if [ -n "$found" ]; then
		val="$1"
		shift
		evar="$(echo ${key:2} | tr '[:lower:]' '[:upper:]' | tr - _)" # delete --, uppercase, replace - with _

#		if [ -n "${!evar}" ]; then echo "${evar} is set in env"; fi

		if grep -q -E "^${evar}=" $NODEENV ; then
			sed -i "s/${evar}=.*$/${evar}=$val/" $NODEENV
		else
			echo "${evar}=$val" >> $NODEENV
		fi

		export ${evar}=$val
	fi
done

for err in $(grep -E '=$' $NODEENV) ; do
	echo "[ERROR] ${err}null (env variable is not set)"
	exit 1
done

exit 0
